package autocode

import "github.com/flipped-aurora/gin-vue-admin/server/service"

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	SysBookTypeApi
	SysBooksApi
	SysStockApi
	SysBookRentLogApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
var (
	excelService                 = service.ServiceGroupApp.ExampleServiceGroup.ExcelService
)
